import { User } from "./user-int";

export const Users: User[] = [
    {
      id: 1,
      name: 'John',
      surname: 'Doe',
      department: 'Sales',
      email: 'john.doe@example.com',
      salary: 60000,
      startDate: new Date(2023, 1, 1),
      finishDate: undefined,
      liveUser: true,
    },
    {
      id: 2,
      name: 'Jane',
      surname: 'Smith',
      department: 'Marketing',
      email: 'jane.smith@example.com',
      salary: 55000,
      startDate: new Date(2023, 2, 1),
      finishDate: undefined,
      liveUser: true,
    },
    {
      id: 3,
      name: 'Mike',
      surname: 'Johnson',
      department: 'HR',
      email: 'mike.johnson@example.com',
      salary: 70000,
      startDate: new Date(2023, 3, 1),
      finishDate: undefined,
      liveUser: true,
    },
    {
      id: 4,
      name: 'Sarah',
      surname: 'Brown',
      department: 'Finance',
      email: 'sarah.brown@example.com',
      salary: 60000,
      startDate: new Date(2023, 4, 1),
      finishDate: undefined,
      liveUser: true,
    },
    {
      id: 5,
      name: 'Alice',
      surname: 'Williams',
      department: 'Operations',
      email: 'alice.williams@example.com',
      salary: 65000,
      startDate: new Date(2023, 5, 1),
      finishDate: undefined,
      liveUser: false,
    },
    {
      id: 6,
      name: 'Peter',
      surname: 'Jones',
      department: 'IT',
      email: 'peter.jones@example.com',
      salary: 75000,
      startDate: new Date(2023, 6, 1),
      finishDate: undefined,
      liveUser: false,
    },
  ];